name: 🚀 Deploy website to develop on push with FTP

on:
  push:
    branches:
      - "@beta"

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.ftp_password }}
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /langnang-beta.ml/htdocs/vue-element-admin/
